sequenceDiagram
    participant User
    participant ReclutadorController
    participant ReclutadorService

    User->>ReclutadorController: GET /api/reclutador
    ReclutadorController->>ReclutadorService: getAllReclutadores()
    ReclutadorService-->>ReclutadorController: List<Reclutador>
    ReclutadorController-->>:User  200 OK

    User->>ReclutadorController: GET /api/reclutador/1
    ReclutadorController->>ReclutadorService: getReclutadorById(1)
    ReclutadorService-->>ReclutadorController: Reclutador
    ReclutadorController-->>:User  200 OK

    User->>ReclutadorController: POST /api/reclutador
    ReclutadorController->>ReclutadorService: saveReclutador(Reclutador)
    ReclutadorService-->>ReclutadorController: Reclutador
    ReclutadorController-->>:User  200 OK

    User->>ReclutadorController: PUT /api/reclutador/1
    ReclutadorController->>ReclutadorService: getReclutadorById(1)
    ReclutadorService-->>ReclutadorController: Reclutador
    ReclutadorController->>ReclutadorService: saveReclutador(Reclutador)
    ReclutadorService-->>ReclutadorController: Reclutador ```plaintext
    ReclutadorController-->>:User   200 OK

    User->>ReclutadorController: DELETE /api/reclutador/1
    ReclutadorController->>ReclutadorService: getReclutadorById(1)
    ReclutadorService-->>ReclutadorController: Reclutador
    ReclutadorController->>ReclutadorService: deleteReclutadorById(1)
    ReclutadorService-->>ReclutadorController: void
    ReclutadorController-->>:User   200 OK